# This is a basic workflow to help you get started with Actions

name: Node.js CI/CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4"

      - name: npm install and test
        run: |
          npm install
          npm test
        env:
          CI: true
      - name: Upload test results
        if: success() || failure() # run this step even if previous step failed
        uses: actions/upload-artifact@v2 # upload test results
        with:
          name: test-results
          path: ./test-results.json

      - name: Create test report
        uses: dorny/test-reporter@v1
        with:
          # artifact: test-results            # artifact name
          name: MOCHA TEST # Name of the check run which will be created
          path: "./*.json" # Path to test results (inside artifact .zip)
          reporter: "mocha-json"

  build:
    # The type of runner that the job will run on
    needs: [test]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
